# Generated by Django 2.0.7 on 2020-05-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0004_auto_20200528_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='controlapp.Tag'),
        ),
    ]
