# Generated by Django 2.0.7 on 2020-05-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlapp', '0006_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
